export const data = {
  data: [
    {
      brand: "Nike",
      supplier: "Nike",
      name: "Men Striped Casual Spread Shirt Super Skinny Fit Low",
      color: "Red",
      size: "XL",
      quantity: 1,
      discount_price: 2850,
      price: 3050,
      off: 25,
      image: "/static/images/shirt.png",
    },
    {
      brand: "Nike",
      supplier: "Nike",
      name: "Men Striped Casual Spread Shirt Super Skinny Fit Low Men Striped Casual Spread Shirt Super Skinny Fit Low",
      color: "Red",
      size: "XL",
      quantity: 1,
      discount_price: 2850,
      price: 3050,
      off: 25,
      image: "/static/images/image 21.png",
    },
    {
      brand: "SPA MASTER Molecular",
      supplier: "zDrop",
      name: "Double door refridgerator",
      color: "Red",
      size: "XL",
      quantity: 1,
      discount_price: 2850,
      price: 3050,
      off: 25,
      image: "/static/images/fridge.png",
    },
  ],
  metadata: {
    delivery_fee: 40,
    delivery_date: "27 January",
    total_item: 2,
    shipping_charge: 600,
    discount: 0,
  },
};
