export const data = {
  branding: {
    brand1: "Nike",
    supplier1: "Nike",
    image1: "/static/images/Daco_24564.png",
    brand2: "SPA MASTER Molecular",
    supplier2: "zDrop",
    image2: "/static/images/kliou.png",
  },
  data1: [
    {
      name: "Men Striped Casual Spread Shirt Super Skinny Fit Low",
      color: "Red",
      size: "XL",
      quantity: 1,
      discount_price: 2850,
      price: 3050,
      off: 25,
      image: "/static/images/shirt.png",
    },
    {
      name: "Polo T-Shirt for men",
      color: "Red",
      size: "XL",
      quantity: 1,
      discount_price: 2850,
      price: 3050,
      off: 25,
      image: "/static/images/image 21.png",
    },
  ],
  data2: [
    {
      name: "Double door refridgerator",
      color: "Gray",
      size: "30L",
      quantity: 1,
      discount_price: 22850,
      price: 30050,
      off: 25,
      image: "/static/images/fridge.png",
    },
  ],
  metadata: {
    delivery_fee: 40,
    delivery_date: "27 January",
    total_item: 3,
    shipping_charge: 600,
    discount: 0,
  },
};
